change base path
Gamify-IT/login-frontend pull request #11
Opened 2022-07-25 14:18 UTC by madebyTimo

change the base path according to the [ADR](https://github.com/Gamify-IT/docs/blob/main/adr/2022-07-21-api-paths.md)

part of https://github.com/Gamify-IT/issues/issues/166

2022-07-25 14:23 UTC, delvh approved these changes

2022-07-25 17:27 UTC, robojones requested changes
Discuss this with overworld team

2022-07-25 19:46 UTC, Gr33ndev approved these changes

2022-07-25 21:32 UTC, madebyTimo commented
I changed the path like discussed with @delvh and @robojones

2022-07-25 21:50 UTC, madebyTimo commented
This is already discussed with overworld team an d an adr exists

2022-07-26 08:15 UTC, robojones approved these changes

2022-07-26 10:50 UTC, merged